version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/

  backend:
    build: ./backend
    container_name: backend
    image: paulmuri/yolo-backend:v1.0.0
    ports:
      - 5001:5001
    depends_on:
      - mongo
      - mongo-express

  frontend:
    build: ./client
    container_name: frontend
    image: paulmuri/yolo-frontend:v1.0.0
    ports:
      - 3000:3000
    volumes:
      - ./client:/client

networks:
  default:
    driver: bridge

volumes:
  mongodb:
