---
- name: Pull image from Docker Hub
  shell: docker pull paulmuri/yolo-backend:v1.0.0

- name: Run container
  shell: docker run -d --name yolo_backend -p 5000:5000 --link mongo_container:mongo_container -e MONGODB_URI=mongodb://mongo/yolo paulmuri/yolo-backend:v1.0.0
