apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: paulmuri/yolo-frontend:v1.0.1
          ports:
            - containerPort: 80  # Expose the container port 80
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:80/api/products"
            - name: REACT_APP_MONGODB_URL
              value: "mongodb://mongodb-service:27017/yolomy"
