apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: paulmuri/yolo-backend:v1.0.1
          ports:
            - containerPort: 5000
          env:
            - name: REACT_APP_MONGODB_URL
              value: "mongodb://mongodb-service:27017/yolomy"